server:
  port: 8010
spring:
  application:
    name: config-server
  cloud:
    config:
      label: main
      server:
        git:
          uri: https://github.com/li1352637064/parentProject/
          search-paths: respo
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
